server:
  port: 8082
  error:
    include-message: always

app:
  feign:
    client:
      config:
        print:
          url: http://ebito-document-generator-clusterip:8083
        data-source:
          url: http://ebito-data-source-clusterip:8085
  rabbitmq:
    queue: ebito_data_aggregator_res_q
    routingkey: ebito_data_aggregator_req_q
    exchange: ebito_exchange

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true


